name: Deploy Nginx

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}

      - name: authenticate to gcloud
        run: |
          echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} | base64 --decode > $HOME/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcloud-service-key.json
          gcloud config set project ${{ secrets.GOOGLE_PROJECT }}
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: build and push the docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/demo/nginx:latest .
          docker push us-central1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/demo/nginx:latest
